export const DUMMY_MUTATION = 'DUMMY_MUTATION'

export const CORDOVA_DEVICEREADY = 'CORDOVA_DEVICEREADY'
export const CORDOVA_ONLINE = 'CORDOVA_ONLINE'
export const CORDOVA_OFFLINE = 'CORDOVA_OFFLINE'
export const CORDOVA_SET_DEVICE = 'CORDOVA_SET_DEVICE'
