export const DUMMY_MUTATION = 'DUMMY_MUTATION'

export const CORDOVA_DEVICEREADY = 'CORDOVA_DEVICEREADY'
export const CORDOVA_ONLINE = 'CORDOVA_ONLINE'
export const CORDOVA_OFFLINE = 'CORDOVA_OFFLINE'
export const CORDOVA_SET_DEVICE = 'CORDOVA_SET_DEVICE'
export const CORDOVA_DEVICE_REGISTER = 'CORDOVA_DEVICE_REGISTER'
export const CORDOVA_NEW_NOTIFICATION = 'CORDOVA_NEW_NOTIFICATION'

export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN'
export const AUTH_SET_USER = 'AUTH_SET_USER'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const TRIPS_SET_TRIPS = 'TRIPS_SET_TRIPS'
export const TRIPS_ADD_TRIPS = 'TRIPS_ADD_TRIPS'
export const TRIPS_SET_MY_TRIPS = 'TRIPS_SET_MY_TRIPS'
export const TRIPS_ADD_MY_TRIPS = 'TRIPS_ADD_MY_TRIPS'