name: Lighthouse CI

on: [push]

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts && npm install -g @lhci/cli@0.15.x

      - name: Build
        run: npm run build

      - name: Run Lighthouse CI
        run: lhci autorun
